# Generated by Django 5.2.5 on 2025-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='guardian',
        ),
        migrations.AddField(
            model_name='guardian',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(default='Not Filled', unique=True),
        ),
    ]
