# Generated by Django 5.2.5 on 2025-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_guardian_guardian_guardian_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='nurse',
        ),
        migrations.AddField(
            model_name='nurse',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
