# Generated by Django 5.2.5 on 2025-09-06 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_nurse_nurse_nurse_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='name',
        ),
        migrations.AddField(
            model_name='nurse',
            name='nurse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
