# Generated by Django 5.2.5 on 2025-09-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_nurse_name_nurse_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Filled', null=True, unique=True),
        ),
    ]
