# Generated by Django 5.2.5 on 2025-08-31 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('condition', models.CharField()),
                ('condition_descriotion', models.TextField()),
                ('process', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('doctor_assigned', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='Users.doctor')),
                ('guardian', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='Users.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField()),
                ('age', models.PositiveIntegerField()),
                ('medical_history', models.TextField()),
                ('floor_no', models.CharField()),
                ('bed_no', models.CharField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_details', to='Patients.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.TextField()),
                ('task', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending')),
                ('assigned_time', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('comleted_time', models.DateTimeField()),
                ('assigned_to', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='Users.nurse')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Patients.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('oxygen_saturation', models.IntegerField()),
                ('check_time', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('checked_by', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_vitals', to='Users.nurse')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='Patients.patients')),
            ],
        ),
    ]
