# Generated by Django 5.2.5 on 2025-09-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_alter_patients_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='condition_descriotion',
            new_name='condition_description',
        ),
    ]
