# Generated by Django 5.2.5 on 2025-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_rename_condition_descriotion_patients_condition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='comleted_time',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending'),
        ),
    ]
