# Generated by Django 5.2.5 on 2025-09-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_remove_tasks_comleted_time_tasks_completed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.DateField(),
        ),
    ]
