# Generated by Django 5.2.5 on 2025-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0005_alter_tasks_assigned_time_alter_tasks_completed_time_and_more'),
        ('Users', '0003_remove_nurse_nurse_nurse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(to='Users.nurse'),
        ),
    ]
