# Generated by Django 5.2.5 on 2025-09-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_remove_tasks_assigned_to_tasks_assigned_to'),
        ('Users', '0003_remove_nurse_nurse_nurse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='Users.nurse'),
        ),
    ]
