# Generated by Django 5.2.5 on 2025-09-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_remove_tasks_assigned_to_tasks_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Patients.patients'),
        ),
    ]
