# Generated by Django 5.2.5 on 2025-09-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0008_alter_tasks_patient'),
        ('Users', '0003_remove_nurse_nurse_nurse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='checked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_vitals', to='Users.nurse'),
        ),
    ]
