# Generated by Django 5.2.5 on 2025-09-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0009_alter_vitals_check_time_alter_vitals_checked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='Patients.patients'),
        ),
    ]
