# Generated by Django 5.2.5 on 2025-09-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0010_alter_vitals_patient'),
        ('Users', '0004_remove_nurse_name_nurse_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldetail',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='bed_no',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='blood_group',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='floor_no',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldetail',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='doctor_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='Users.doctor'),
        ),
    ]
